project_id = "qwkpsmfjrhjwjrdrykwt"

[functions.motivational-quote]
verify_jwt = false

[functions.habit-generator]
verify_jwt = false

[functions.consistency-coach]
verify_jwt = false

[functions.skill-recommender]
verify_jwt = false

[functions.team-challenge-generator]
verify_jwt = false

[functions.drift-corrective-plan]
verify_jwt = false

[functions.todo-suggester]
verify_jwt = false

[functions.generate-identity-logo]
verify_jwt = false
